config/server.py
lib/aff4_objects/user_managers.py

Incorrectly reverted commits were:
1. 64357ebf4b710b0c1150de6207a23b2c8733507d
2. 198b244060422b13788ce380e0d3a9cfe79cb7f3

Replaying previously incorrectly reverted commits

---

gui/api_value_renderers.py
gui/api_value_renderers_test.py
run_tests.py

* Fixing a bug with ApiGrrMessageRenderer not rendering the payload.
* Changed exclude_tests flag default value to [], otherwise tests were not running correctly.

Fixing ApiGrrMessageRenderer to render proper paylod + minor fixes.

---

lib/aff4_test.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/165)

Added unit test

---

tools/config_updater.py

Just changed regex to allow entering an https:// url during initialization.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/169)

Enabled https regex for AdminUI

---

lib/data_stores/mysql_advanced_data_store.py

remove unused variable
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/167)

unused variable

---

lib/flows/cron/compactors.py

Would this be a safer way to help prevent race conditions here?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/193)

Altered PackedVersionCollection to only delete what it selected

---

lib/hunts/standard.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/194)

Altered ProcessHuntResults to only delete what it selected

---

setup.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/195)

Fixed install for new local js files

---

gui/api_plugins/aff4.py
gui/plugins/hunt_view.py
gui/plugins/inspect_view.py
gui/plugins/searchclient.py
lib/aff4.py
lib/aff4_objects/collections.py
lib/aff4_objects/standard.py
lib/data_store.py
lib/data_store_test.py
lib/data_stores/fake_data_store.py
lib/data_stores/mysql_advanced_data_store.py
lib/data_stores/mysql_data_store.py
lib/data_stores/mysql_data_store_test.py
lib/data_stores/sqlite_data_store.py
lib/data_stores/sqlite_data_store_test.py
lib/flow.py
lib/flow_test.py
lib/flows/general/timelines.py
lib/front_end_test.py
lib/keyword_index.py
lib/queue_manager.py
lib/queue_manager_test.py
worker/worker_test.py

There is still a lot of work to be done - there are no actual
implementations yet (except for FakeDataStore) and once we add them,
we will also need more tests - but it's a first step in the right
direction.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/242)

A fist stab at removing the ResolveRegex interface.

---

scripts/install_script_ubuntu.sh

Fixes https://github.com/google/grr/issues/346

Rename to python-pytsk3 to match PPA change.

---

grr/config/grr-response-server/setup.py
grr/lib/distro_entry.py

Added in an entry point as per conversation in [GRR-Users group- Separation of Services Question]( https://groups.google.com/forum/#!topic/grr-users/Be6f0aig9iE ).

Create Dataserver Entry Point

---

grr/tools/config_updater.py

Noticed that it jumped from "Step 3" to "Step 5", so I fixed it.

Updated Steps in config_updater.py

---

grr/lib/data_stores/http_data_store.py

If we get an empty or short response, the process will loop forever trying to read the rest of the data.  Prevent this by raising an exception if the response is not long enough.  I saw this issue on other nodes when a data server ran out of file descriptors.
An alternative would be to make sure _ReadReply returns None for a more graceful retry.  What do you think?
I guess this is not a common issue, because processes stuck at 100% CPU forever tends to stick out.

Prevent infinite loop when data store fails

---

grr/lib/builders/osx.py
install_data/etc/grr-server.yaml
install_data/macosx/client/Distribution.xml.in

I'll remove the packagemaker files in a following change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/grr/461)

Stop using packagemaker on OS X.

---

grr/server/data_server/manager.py
grr/server/data_server/rebalance.py

Ref: https://github.com/google/grr/issues/467

Fix deserialization issues in DataServer manager

---

grr/proto/api.proto

Fix client_rate < 1 display problem

---

grr/lib/maintenance_utils.py

This fixes the problem described #480.

maintenance_utils: Disallow empty user names

---

grr/config/grr-response-server/setup.py

Fixes issue https://github.com/google/grr/issues/506

add oauth2client dep

---

grr/lib/data_stores/sqlite_data_store.py

This should take care of Github issue #472.

Operate SQLite datastore in WAL mode

---

grr/client/grr_response_client/client_utils_common.py

netsh arg list fix

---

grr/client/grr_response_client/client_utils_common.py

Add additional whitelisting command for just fetching the enabled
Windows Firewall rules

more Windows Firewall cmd whitelisting

---

grr/server/grr_response_server/databases/mysql_clients.py

This fixes https://github.com/google/grr/issues/716

Make mysql_clients.py/RemoveClientLabels accept arbitrary iterables.

---

grr/proto/grr_response_proto/api/metadata.proto
grr/server/grr_response_server/gui/api_call_robot_router.py
grr/server/grr_response_server/gui/api_call_robot_router_test.py
grr/server/grr_response_server/gui/api_call_router.py
grr/server/grr_response_server/gui/api_call_router_with_approval_checks.py
grr/server/grr_response_server/gui/api_call_router_without_checks.py
grr/server/grr_response_server/gui/api_labels_restricted_call_router.py
grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/root/api_root_router.py

- Add the method to all routers
- Create a protobuf message for its result
- Update api_call_robot_router_test.py to consider this method as implemented

Add API method which will be used to get the OpenAPI description

---

grr/server/grr_response_server/gui/ui/components/client/client.ng.html
grr/server/grr_response_server/gui/ui/components/client/client.scss
grr/server/grr_response_server/gui/ui/components/client/client.ts
grr/server/grr_response_server/gui/ui/components/client/module.ts
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/client_add_label_dialog.ng.html
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/client_add_label_dialog.scss
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/client_add_label_dialog.ts
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/client_add_label_dialog_test.ts
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/module.ts
grr/server/grr_response_server/gui/ui/lib/api/api_interfaces.ts
grr/server/grr_response_server/gui/ui/lib/api/http_api_service.ts
grr/server/grr_response_server/gui/ui/lib/api_translation/client.ts
grr/server/grr_response_server/gui/ui/lib/api_translation/client_test.ts
grr/server/grr_response_server/gui/ui/lib/models/client.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade_test.ts
grr/server/grr_response_server/gui/ui/store/config_facade.ts
grr/server/grr_response_server/gui/ui/store/config_facade_test.ts
grr/server/grr_response_server/gui/ui/store/config_facade_test_util.ts

Added a button to use for adding a label to a client

Add label to client

---

api_client/python/grr_api_client/api.py
api_client/python/grr_api_client/metadata.py
grr/proto/grr_response_proto/api/metadata.proto
grr/proto/grr_response_proto/tests.proto
grr/server/grr_response_server/gui/api_call_robot_router.py
grr/server/grr_response_server/gui/api_call_router_without_checks.py
grr/server/grr_response_server/gui/api_integration_tests/metadata_test.py
grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py
grr/server/grr_response_server/gui/root/api_root_router.py

- Implement a new GRR API method that generates and returns the OpenAPI description of the GRR API
- Add associated Python client library method
- Write unit tests and an integration test
EDIT:
Please note that I use the ":+1:" emoji to mark comments that I've addressed in a yet to be created/pushed commit at the time of the emoji usage.

OpenAPI description generation for the GRR API

---

grr/core/grr_response_core/lib/rdfvalues/osquery.py
grr/proto/grr_response_proto/osquery.proto
grr/server/grr_response_server/flow_base.py
grr/server/grr_response_server/flows/general/osquery.py
grr/server/grr_response_server/flows/general/osquery_test.py

Report the first 10 rows, together with the total number of rows as "Progress".
This PR only contains the backend changes.

Add progress info for the Osquery Flow (Backend)

---

grr/server/grr_response_server/bin/grrafana.py

The constructor of the `JSONResponse` struct is a bit hacky and complicated. Although it has been discussed in #832 (mainly in [this section](https://github.com/google/grr/pull/832#discussion_r481227607)), @mbushkov suggested that we try and remove the constructor.

Removed JSONResponse constructor

---

grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.ng.html
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.scss
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.ts
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor_test.ts
grr/server/grr_response_server/gui/ui/components/code_editor/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ng.html
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.scss
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ts
grr/server/grr_response_server/gui/ui/main.scss
grr/server/grr_response_server/gui/ui/package-lock.json
grr/server/grr_response_server/gui/ui/package.json

Adding a basic editor with proper code editor font, line numbers, basic SQL syntax highlighting

---

grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.ng.html
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.scss
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.ts
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor_test.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ng.html
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.scss
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ts

This is how the final result looks like:

Upgrade editor and prepare for the osquery helper

---

grr/server/grr_response_server/gui/ui/angular.json
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor.scss
grr/server/grr_response_server/gui/ui/components/code_editor/code_editor_test.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ng.html
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.scss
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form_test.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_query_helper/osquery_query_helper_test.ts
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ng.html
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.scss
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ts
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details_test.ts
grr/server/grr_response_server/gui/ui/lib/api/api_interfaces.ts

Back end PR: https://github.com/google/grr/pull/901

Front end changes for file collection in the osquery flow

---

grr/client/grr_response_client/client_actions/osquery.py
grr/client/grr_response_client/client_actions/osquery_test.py
grr/core/grr_response_core/lib/rdfvalues/osquery.py
grr/proto/grr_response_proto/osquery.proto
grr/server/grr_response_server/flows/general/osquery.py
grr/server/grr_response_server/flows/general/osquery_test.py
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_form_test.ts
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ng.html
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details.ts
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/osquery_details_test.ts
grr/server/grr_response_server/gui/ui/lib/api/api_interfaces.ts
grr/test_lib/osquery_test_lib.py

MVP error reporting

---

.github/workflows/build.yml
appveyor/e2e_tests/run_e2e_tests.sh

Windows 2016 is deprecated: https://github.com/actions/virtual-environments/issues/4312

Update Windows version for GithubActions

---

grr/server/grr_response_server/bin/worker_test.py
grr/server/grr_response_server/client_index.py
grr/server/grr_response_server/databases/db.py
grr/server/grr_response_server/databases/db_flows_test.py
grr/server/grr_response_server/databases/mem.py
grr/server/grr_response_server/databases/mysql.py
grr/server/grr_response_server/databases/mysql_migration.py
grr/server/grr_response_server/databases/mysql_migrations/0014.sql
grr/server/grr_response_server/databases/mysql_paths.py
grr/server/grr_response_server/flows/cron/system_test.py
grr/server/grr_response_server/flows/general/administrative_test.py
grr/server/grr_response_server/flows/general/export.py
grr/server/grr_response_server/gui/api_plugins/client.py
grr/server/grr_response_server/gui/api_plugins/user.py
grr/server/grr_response_server/gui/ui/components/client_add_label_dialog/module.ts
grr/server/grr_response_server/gui/ui/components/client_details/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_form/osquery_query_helper/module.ts
grr/server/grr_response_server/gui/ui/components/flow_args_view/module.ts
grr/server/grr_response_server/gui/ui/components/flow_details/plugins/module.ts
grr/server/grr_response_server/gui/ui/components/hunt/hunt_page/hunt_results/hunt_results.ng.html
grr/server/grr_response_server/gui/ui/components/hunt/hunt_page/hunt_results/hunt_results_test.ts
grr/server/grr_response_server/gui/ui/lib/api/http_api_service.ts
grr/server/grr_response_server/gui/ui/lib/api_translation/result.ts
grr/server/grr_response_server/gui/ui/lib/models/result.ts
grr/server/grr_response_server/stats_server.py

* Making monitoring server IPv4-compatible.
* Fixing issues with MySQL and 0 seconds from epoch timestamps (MySQL expects timestamps starting from 1 second from epoch).
* MySQL optimisations to prevent locking issues in client_paths table. NOTE: this will require setting `log_bin_trust_function_creators=1` in the MySQL config.
* UIv2 work.

Syncing recent changes.

---

grr/client_builder/grr_response_client_builder/build_helpers.py

Adds pyinstaller workaround for 'ipaddress' library

Adds pyinstaller workaround for 'ipaddress' library

---

grr/core/grr_response_core/config/output_plugins.py
grr/proto/grr_response_proto/output_plugin.proto
grr/server/grr_response_server/output_plugins/__init__.py
grr/server/grr_response_server/output_plugins/webhook_plugin.py
grr/server/grr_response_server/output_plugins/webhook_plugin_test.py

This PR proposes a Webhook Output Plugin for GRR to enable event driven integrations with third party tooling.

Webhook Output Plugin
