parsers/wmi_parser.py

Workers/Enrollers can get hung up if this is not properly handled.  I'm not sure if this was just a missing TypeError or if there is some other behavior that is causing the WMI disk stuff to have TypeError instead of ValueError.  result.get("Size") will return None and then int() fails with TypeError as described here: https://github.com/google/grr/issues/87
This fix appears to top the WMI disk artifacts from causing worker/enroller hangups.

Fixed missing TypeError exception

---

scripts/install_script_ubuntu.sh

This was required so that I could pass the http[s]_proxy environment vars to easy_install.

Add -E to sudo easy_install selenium

---

.gitignore
.travis.yml
artifacts/Makefile
before_install.sh
install.sh
lib/test_lib.py
requirements.txt
run_tests.py
run_tests.sh

This pull request introduces a first version of the travis build. It makes the necessary changes required to get this running on travis systems.
I'm introducing two separate installation scripts that are responsible for different stages of setting up the grr environment in order to be able to run it on travis:
* `before_install.sh` installs all the necessary dependencies on the vanilla travis system. This includes ubuntu repository `apt-get install` commands and `apt-get install` commands from `plaso`,  and some manual installation of `.deb` files. These are explained in detail below.
* `install.sh` fires up the `pip` installation of packages and runs the required `make` command on the pure source in order to do the necessary building for artifacts and protobufs.
The several `apt-get …

Basic travis build script

---

lib/aff4_objects/filestore.py

This forced modification of the regex causes a brutal performance hit (7s queries vs 0.3s queries in the tested example).  It would be better to send the regex as desired in any calls to this.  This appears to be what it is doing in filestore_stats.py, but I'm not clear on all of the other places where this is getting called.  This passes unit tests and I am going to begin testing it in a live test environment, but any heads up on other places where this change needs to be accounted for would be appreciated.

Removed unecessary forced regex

---

gui/api_plugins/stats.py

This may not be the best way to solve this, but the normal use only involves _ and it gets escaped to \\_ so the datastore is unable to optimize against using a regex since ultimately the whole query becomes the full attribute and not a regex at all.  This changes the queries for even a 1hr window from multiple 5+ second queries all queries being sub 1s.

Removed unnecessary regex escaping

---

config/centos/grr.spec.in
lib/build.py

This should fix the build issues.  The expectation is that %install empties BUILDROOT and then copies BUILD into BUILDROOT (typically using make install).  Because these were being used as the same dir RHEL blows everything away and then fails to pack.  This change should assemble the client in BUILD as normal and then declare BUILDROOT as the target and then the cp command replaces what make install would normally do.

RPM Build fixes

---

lib/data_stores/mysql_advanced_data_store.py

This works in a test environment so if GRR isn't going to try to store larger things in the value field this is a slightly better schema.

Switched from LONGBLOB to MEDIUMBLOB for value storage

---

config/server.py
lib/access_control_test.py
lib/aff4_objects/security.py

config_lib is not instantiated except for constants when LIFETIME is defined.  So, ACL.token_expiry cannot override LIFETIME and thus LIFETIME is not used in CheckAccess().

ACL Token expiry

---

lib/build.py

This isn't really an error for the majority of cases where build.py is getting loaded so lowering to a warning to clear up logs.  New users have also reported feelings of confusion and doubt when encountering this error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/172)

Lowered severity of PyInstaller import error

---

lib/flows/cron/data_retention.py

These hunts can take longer than 6hrs to successfully run if there is a larger amount of data to get through.  I have had instances of both complete the deletes, but still report timeout errors.  1d seems like a reasonable limit for a weekly cron.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/214)

Extended flow durations to 1d

---

lib/client_index.py
lib/flows/general/ca_enroller.py
lib/flows/general/discovery.py

I left the Creates in the UI alone since they shouldn't ever be encountered at a rate that causes problems and it should ensure that the client index does get added to the root index so that nothing is fundamentally altered in how everything is getting stored.
I will be testing this soon against MySQLAdvanced with a much larger connection pool to ensure this solves the interrogate hunt performance issues.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/grr/220)

Interrogate fix

---

lib/distro_entry.py

Operating system detection for setting up server.yml non functional on CentOS to spite binary compatibility.  Added a case for this to GetDistro().

Add case to GetDistro() for CentOS linux.

---

grr/lib/config_lib.py

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

grr/artifacts/makefile.py

- The 3102 server was released before a large artifact rename change so the
server needs to use the older version.

Set artifacts to 20160617 release for 3102 branch.

---

README.md

The screenshots in the README.md are rendered incorrectly by GitHub.
This is because GitHub cannot handle whitespace in hyperlinks.
This PR resolves this issue by replacing whitespaces with `%20`.

Fix hyperlinks of screenshots in README.md

---

grr/server/grr_response_server/gui/api_plugins/config.py

I noticed this field wasn't redacted on the Settings page in the Admin UI. This JSON will contain a private key, so I believe it shouldn't be shown here, in the same fashion other private keys and passwords are not shown.

Redact Bigquery Service Account JSON

---

grr/client/grr_response_client/client_utils_common.py

Add whitelist for Windows netsh.exe <…> command, to be able to fetch the windows firewall
configuration.

Additional whitelist command

---

grr/core/grr_response_core/config/gui.py
grr/server/grr_response_server/gui/validate_iap.py
grr/server/grr_response_server/gui/webauth.py
grr/server/grr_response_server/gui/webauth_test.py
grr/server/setup.py

This PR Adds Authentication support from Google's IAP service. The extension pulls the x-google-iap-jwt-assertion header from IAP and generates a new user for that header via the 'sub' claim. Authorization is delegated via IAP.

[IAP] Add IAP Web Auth Support

---

.travis.yml

[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

Travis CI: 'sudo' tag is now deprecated

---

monitoring/grafana/grr_grafanalib_dashboards/dashboards_for_use/admin_ui.json
monitoring/grafana/grr_grafanalib_dashboards/dashboards_for_use/frontends.json
monitoring/grafana/grr_grafanalib_dashboards/dashboards_for_use/workers.json
monitoring/grafana/grr_grafanalib_dashboards/dashboards_to_generate/admin_ui.dashboard.py
monitoring/grafana/grr_grafanalib_dashboards/dashboards_to_generate/frontends.dashboard.py
monitoring/grafana/grr_grafanalib_dashboards/dashboards_to_generate/workers.dashboard.py
monitoring/grafana/grr_grafanalib_dashboards/reusable_panels.py

The panels and graphs in the previously submitted Grafana dashboards (see #787 and the rest of the corresponding PRs) were not all aggregated by some label. What this practically means is that some graphs would explode if more GRR server component instances were to be added to a deployment.
We want to change that so the number of lines in a certain graph would not depend on the number of instances of a certain GRR server component (for example, can be other labels as well).
For example; for the graph "API Method Latency Rate" in the AdminUI dashboard, if it would not be aggregated (the existing situation), then if _x_ more AdminUI instances were in the deployment, each instance with about _y_ different API methods used, then the graph would have _xy_ lines, which can be a lot depending on …

Aggregate GRR server components dashboards data

---

grr/server/grr_response_server/gui/ui/components/client/client.ng.html
grr/server/grr_response_server/gui/ui/components/client_search/client_search_test.ts
grr/server/grr_response_server/gui/ui/components/timestamp/module.ts
grr/server/grr_response_server/gui/ui/components/timestamp/relative_timestamp_pipe.ts
grr/server/grr_response_server/gui/ui/components/timestamp/timestamp.ng.html
grr/server/grr_response_server/gui/ui/components/timestamp/timestamp.scss
grr/server/grr_response_server/gui/ui/components/timestamp/timestamp.ts
grr/server/grr_response_server/gui/ui/components/timestamp/timestamp_test.ts
grr/server/grr_response_server/gui/ui/material-theme.scss

Added some changes to the timestamp component. Now, it shows the absolute format as a base format, and the tooltip contains a relative timestamp, showing how much time passed since then. Also, I added a long version, which doesn't show the relative timestamp in a tooltip, but inline instead. The long version also has a copy icon, for easy and fast copy.

Update timestamp in UIv2 to show absolute timestamp for short format

---

api_client/python/grr_api_client/hunt.py
grr/proto/grr_response_proto/api/timeline.proto
grr/server/grr_response_server/gui/api_call_router.py
grr/server/grr_response_server/gui/api_integration_tests/hunt_test.py
grr/server/grr_response_server/gui/api_plugins/timeline.py
grr/server/grr_response_server/gui/api_plugins/timeline_test.py

- Update the ApiGetCollectedHuntTimelinesArgs protobuf message to hold the format
- Update the API router and handler
- Update the Python API client to accept the format argument
- Update/Add tests

Add format argument for hunt timelines collection

---

grr/server/grr_response_server/gui/ui/components/client/client.ts
grr/server/grr_response_server/gui/ui/components/config/config.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade_test.ts

Add polling of client data to update client info, only when the UI is subscribed to the selectedClient$ observable.

Poll client data when subscribed

---

debian/grr-server@.service
docker/docker-entrypoint.sh
grr/core/grr_response_core/lib/config_lib.py
grr/server/grr_response_server/server_startup.py

- Set `disallow_missing_config_definitions` flag to True for server components in `server_startup.py`
- Remove the flag from Debian and Docker deployment scripts
Please see [issue 671](https://github.com/google/grr/issues/671) for more context.

Set disallow_missing_config_definitions as True by default for server components

---

grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

In this PR, logic is added to define the primitive types only once, in the `components` field of the root [`OpenAPI Object`](https://swagger.io/specification/#openapi-object), then use `Reference Object`s to refer to them, just like we do with composite types. Previously, primitive types would have their schema added whenever they were used (for example for describing route parameters).
This change reduces the complexity of the code, as the need to differentiate between composite types and primitive types throughout the description generation logic is reduced and it also can reduce the size of the generated JSON (depending on how many times primitive types are used).

Use references to primitive types in OpenAPI description of the GRR API

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

In this PR, I:
- change type annotations for local variables to use PEP 526 ones instead of comment based ones as in PEP 484;
- remove references from unions to the `PrimitiveSchema` type in type annotations where it is not necessary anymore due to the previous change to using `Reference Object`s for primitive types' schemas as well (introduced [here](https://github.com/google/grr/pull/824)).

Improve OpenAPI-related type annotations

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

Split the functionality of `_GetReferenceObject` by introducing a new function: `_GetArraySchema`.
This approach removes the `boolean` flag previously used by `_GetReferenceObject`, better separates concerns of the functions and helps remove type ambiguity.

Split _GetReferenceObject function into 2 functions 

---

grr/proto/grr_response_proto/tests.proto
grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

In this PR I introduce OpenAPI description generation for `protobuf.map` types, as well as a test that verifies the generated output. 
There is a difference between `protobuf.map` and the OpenAPI Specification descriptions of maps: `protobuf.map`s support ["any integral or string type" for the keys' type](https://developers.google.com/protocol-buffers/docs/proto#maps), whereas the OpenAPI Specification allows only [`string` for the keys' type](https://swagger.io/docs/specification/data-models/dictionaries/).
In order to let users know the actual type of the keys, I use the same approach as in the case of [`protobuf.oneof` semantics](https://github.com/google/grr/pull/827), which is to specify the actual types in a comment stored in the `description` field of the `schema` dictionary used …

Implement OpenAPI description generation for Protobuf maps

---

grr/server/grr_response_server/gui/api_call_router.py

`GetLastClientIPAddress` was the only router method missing a `@Category` decorator.

Add Category decorator for GetLastClientIPAddress router method

---

grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

In this PR I introduce code that figures out if there are multiple routes associated to a singe router method which actually just describe a single route with optional path arguments. The implementation is a bit more generic than what is currently necessary for the routes described in `api_call_router.py`, in the sense that it also treats multiple routes with different HTTP methods associated with a single router method, as well as multiple routes with the same HTTP method but different path components and different required / optional path arguments for the same router method. I implemented it this way because it covers more theoretically possible cases (but which aren't necessarily a good practice, such as using the same router method for routes with different HTTP methods) and because …

Detect optional path arguments in GRR API routes and present them in the OpenAPI description

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

In [PR 837](https://github.com/google/grr/pull/837) I introduced the code that detects optional path parameters from the GRR API routes and describes them accordingly in the generated OpenAPI description. That implementation was based on a trie in order to represent the routes. In this PR I introduce an alternative solution that replaces the trie with lists, improving readability, but affecting the time complexity.
The core idea is the same as in the trie-based solution: we want to find and group routes that have a common "stem" route and continue to extend it with **consecutive terminal path parameters** (e.g. `_prefix_/arg1`, `_prefix_/arg1/arg2` and `_prefix_/arg1/arg2/arg3` can be reduced to `_prefix_/arg1/arg2/arg3` with `required_args = [arg1]` and `optional_args = [arg2, arg3]`). …

Refactor OpenAPI optional path parameters detection to use lists instead of a trie

---

grr/proto/grr_response_proto/tests.proto
grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

In this PR I extract the [`SemanticDescriptor` `sem_type`](https://github.com/google/grr/blob/b472626b6ff4d05b24269a7ce52419d00a847607/grr/proto/grr_response_proto/semantic.proto#L8) protobuf field option and use its `type` field to describe message fields and parameters in the generated OpenAPI description of the GRR API.
I use a dictionary of supported RDF types for which we have an OpenAPI schema including a description which specifies what that type actually represents. The RDF types included are all the ones defined in [`grr_response_core/lib/rdfvalue.py`](https://github.com/google/grr/blob/master/grr/core/grr_response_core/lib/rdfvalue.py) and [`grr_response_core/lib/rdfvalues/paths.py`](https://github.com/google/grr/blob/master/grr/core/grr_response_core/lib/rdfvalues/paths.py) …

Extract type from protobuf semantic field option and use it in OpenAPI description

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

In this PR I change the format of the OpenAPI `operationId` associated with each route to consist only of the router method's id. This will have a direct effect on the header displayed in the documentation generated with ReDoc (using default parameters).
_Please note that I use the ":thumbsup:" emoji to mark comments that I've addressed in a yet to be created / pushed commit._

Use router method name as router id in OpenAPI description

---

grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

After [discussing with @panhania and @bgalehouse](https://github.com/google/grr/pull/843#discussion_r485540364), I learned that I was wrongly using plural nouns as attributes. This PR refactors the variable names and comments where nouns in their plural form were used as attributes by removing their plurality marker.

Refactor variable names and comments with noun attributes from OpenAPI code

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

Replace _AddPrimitiveTypeSchemas and _AddRDFTypeSchemas by using their code inline in OpenAPI handler

Refactor protobuf primitive and RDF type schemas usage in OpenAPI handler

---

grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

In this PR I convert protobuf message field names from snake_case to camelCase when using them in the generated OpenAPI description. These field names are used when specifying the expected parameter and the expected result schemas.
_Please note that I use the ":thumbsup:" emoji to mark comments that I've addressed in a yet to be created / pushed commit._

Use camelCase for property names in OpenAPI description

---

grr/server/grr_response_server/gui/api_plugins/metadata.py

In this PR I replace the `/api/...` path component from the paths annotated to router methods with `/api/v2/...` in the generated OpenAPI description in order to point users to routes of the API that return the described fields with the described level of nesting.

Use `/api/v2/...` when describing route paths in OpenAPI description

---

grr/server/grr_response_server/gui/api_plugins/metadata.py
grr/server/grr_response_server/gui/api_plugins/metadata_test.py

A [couple of routes](https://github.com/google/grr/blob/77c87c29b4f5c76cbe26ed7a48a37a32a2c12c24/grr/server/grr_response_server/gui/api_call_router.py#L350-L363) have a trailing "/" in their path. This caused an extra empty string to be added to the list of path components when using `path.split("/")` and in turn, this caused the optional path parameter extraction algorithm to fail because the route adding a new path parameter would actually add 2 new path components, instead of one (the actual path parameter).
This PR solves this bug and adds to an existing test in order to verify this case too,

Fix bug in OpenAPI description generation related to trailing slashes in routes

---

grr/server/grr_response_server/bin/grrafana.py
grr/server/grr_response_server/bin/grrafana_test.py
grr/server/grr_response_server/fleetspeak_utils.py
grr/server/grr_response_server/fleetspeak_utils_test.py

Following a discussion on google/fleetspeak#281, we would like to pass a time range to the `/query` API endpoint rather than a specified `limit`. This way, we can retrieve much more meaningful and more accurate datapoints from Fleetspeak's database.
Note that this PR depends on google/fleetspeak#294, and will work only once google/fleetspeak#294 is merged.

On query support for time range

---

grr/server/grr_response_server/bin/grrafana.py
grr/server/grr_response_server/bin/grrafana_test.py
monitoring/grafana/grr_grafanalib_dashboards/config.py
monitoring/grafana/grr_grafanalib_dashboards/fleetspeak_enabled_setup/dashboards_for_use/client_load_stats.json
monitoring/grafana/grr_grafanalib_dashboards/fleetspeak_enabled_setup/dashboards_to_generate/client_load_stats.dashboard.py

This PR introduces a new [Grafana Dashboard](https://grafana.com/docs/grafana/latest/features/dashboard/dashboards/#dashboard-overview) to GRR for the **Client Load Stats** page. The statistics in the dashboard are gathered from the Fleetspeak client (rather than the current page that gathers its information from the GRR client). The statistics are queried from Grafana using [JSON Datasource plugin](https://github.com/simPod/grafana-json-datasource), and are processed in GRRafana HTTP server (the full details of GRRafana HTTP server and the interaction are described in #832).
The changes directly related to the dashboard are in the Python package `grr_grafanalib_dashboards`, as presented in #783.
Here's a snapshot of the new dashboard:
You may notice that this dashboard contains a Grafana …

Grafana Dashboard for Client Load Stats

---

grr/server/grr_response_server/bin/grr_server.py
grr/test/grr_response_test/lib/self_contained_components.py

Added start up configurations to make GRRafana HTTP server a component of GRR Response Server.
Note that I only added configs where Fleetspeak is enabled, as GRRafana can only be used on a FS-based setup (no legacy).

Productionized GRRafana 

---

grr/server/grr_response_server/bin/grrafana.py
grr/server/grr_response_server/bin/grrafana_test.py

This PR extends GRRafana HTTP server introduced in #832 by adding new metrics that can be fetched.
These new metrics are the ones that appear in GRR's Statistics page (for reference, you can check out one of the metrics fetched within this page [here](https://github.com/google/grr/blob/0e03976c5c5b694c210c0f392581364ddefa1f4b/grr/server/grr_response_server/gui/api_plugins/report_plugins/client_report_plugins.py#L194)).
The metrics introduced to the server (and Grafana, in turn) are:
- OS Release Version Breakdown
- OS Platform Breakdown
- Client Version
All metrics are available in the interface for 1, 7, 14 and 30 days, and are shown in a table format (similar to the way it currently is in the Statistics page within GRR AdminUI).
In order to support this new metric (which unlike Client …

GRRafana: Add support to query Client Breakdown Statistics

---

grr/server/grr_response_server/gui/ui/lib/queued_exhaust_map.ts
grr/server/grr_response_server/gui/ui/lib/queued_exhaust_map_test.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade.ts
grr/server/grr_response_server/gui/ui/store/client_page_facade_test.ts

The old queryFlowResults implementation would discard requests for more data if another one is currently in progress, even if the new requests are coming from different flows. This caused only the first flow which requests results to get them. 
The new implementation groups requests by flows so that different flows don't affect each other. Additionaly, within the same group, it effectively creates a queue of size 1 for any pending requests, which ensures that the last request that was made will always be satisfied.

Fix error in queryFlowResults functionality

---

grr/core/grr_response_core/config/server.py
grr/server/grr_response_server/bin/grrafana.py

Made the server and port of GRRafana server configurable. For reference, this is similar to how the [default crash limit](https://github.com/google/grr/blob/0e03976c5c5b694c210c0f392581364ddefa1f4b/grr/server/grr_response_server/rdfvalues/hunts.py#L83) of hunts [are configured](https://github.com/google/grr/blob/fe2563069b0a8c6fdea3fe24a3c938c16391a5e3/grr/core/grr_response_core/config/server.py#L246).
I do have one small question though - do we want to let these settings be set up during `grr_config_updater initialize` as well, similar to the way the [MySQL port](https://github.com/google/grr/blob/fe2563069b0a8c6fdea3fe24a3c938c16391a5e3/grr/server/grr_response_server/bin/config_updater.py#L127) is set up?

Added server and port configurations for GRRafana server

---

monitoring/grafana/grr_grafanalib_dashboards/fleetspeak_enabled_setup/dashboards_for_use/fleetspeak.json
monitoring/grafana/grr_grafanalib_dashboards/fleetspeak_enabled_setup/dashboards_to_generate/fleetspeak.dashboard.py

Changed the datasource from `fleetspeak` to `grr-server`, so that users don't need to set up two different [Grafana datasources](https://grafana.com/docs/grafana/latest/datasources/).
This closes [this discussion](https://github.com/google/grr-doc/pull/132#discussion_r534102231) on [google/grr-doc](https://github.com/google/grr-doc).

Changed datasource of Fleetspeak Grafana dashboard

---

.github/workflows/build.yml
grr/server/setup.py

Hello, everyone in the community! 🙂
Based on @Tati1701 good work (#969), I create new PR for reflect my suggestion.
Please refer to this link for discussions with my proposal: https://github.com/google/grr/pull/969#discussion_r849424559
However, `test-ubuntu-e2e` is still not working, so it needs to be resolved by that PR or a new PR.
If you have any comments on this PR, please feel free to leave a thread! 🙌

Fix: `pytest` version ,`soft_unicode` from `markupsafe` error on GitHub Actions

---

appveyor/e2e_tests/run_e2e_tests.sh

This change was accidentally rolled back in my latest commit [1].
[1] https://github.com/google/grr/commit/be9fded48e2b066c603b7965da6c22f10e7ee3ad

Adding user to fix e2e tests.

---

api_client/python/setup.py
grr/core/setup.py

Hello, everyone in the community! 🙂
We have used GRR's API in many DFIR open sources to take advantage of GRR's superior functionality.
However, in order to avoid errors in the deployment process in GRR's API,
we have limited the version of the `cryptography` module.
Currently, these restrictions are a problem at new devices or platforms and require version updates.
So I raised an issue (#967) about this, and we decided to proceed with the version update.
We will continue to monitor and improve the side effect.
I hope this PR will have a good effect on other DFIR projects.
Fixes #967

Update: `cryptography` version `2.9.2` to `3.3.2` by issue

---

grr/core/grr_response_core/config/build.py

This issue was fixed by PyInstaller in a newer version, but since we still use the old one we need to patch it ourselves. It can be removed as soon as we upgrade. For more information, see https://github.com/pyinstaller/pyinstaller/pull/5770/files

Fix missing DLL issue Windows machines without VCRuntime

---

CHANGELOG
grr/core/grr_response_core/config/logging.py
grr/server/grr_response_server/base_stats_server.py
grr/server/grr_response_server/stats_server.py
grr/server/grr_response_server/stats_server_test.py

Added configuration option to specify the stats server IP address to bind to. Default option will remain 127.0.0.1 loopback.
I use separate containers (Pods) for the GRR components and need the ability to expose the Prometheus  metric endpoints to  Kubernetes Services which forwards the results to a Prometheus operator. With the current setup the metrics are only accessible from within the container's local loopback device (localhost). 
Edit:
Taking @max-vogler

Add Monitoring.http_address to expose Prometheus stats server

---

CHANGELOG
grr/server/grr_response_server/output_plugins/elasticsearch_plugin.py
grr/server/grr_response_server/output_plugins/elasticsearch_plugin_test.py

Updates the elasticsearch output plugin to conform to additional requirements set by the elasticcsearch [_bulk api.](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/docs-bulk.html)
>The final line of data must end with a newline character \n. Each newline character may be preceded by a carriage return \r. When sending NDJSON data to the _bulk endpoint, use a Content-Type header of application/json or application/x-ndjson.
Adds a changelog entry for the above change.
Edit: 
Added a test to ensure one of the elastic approved content type headers is used.
Added a test to ensure the post body to _bulk ends with a '\n'.
------
Closes #990

Update elasticsearch output plugin.

---

CHANGELOG.md
grr/client/grr_response_client/client_actions/file_finder.py
grr/client/grr_response_client/client_actions/file_finder_test.py
grr/client/setup.py
grr/client_builder/setup.py
grr/core/grr_response_core/config/artifacts.py
grr/core/grr_response_core/lib/parsers/linux_release_parser.py
grr/core/grr_response_core/lib/rdfvalue.py
grr/core/grr_response_core/lib/rdfvalues/structs.py
grr/core/grr_response_core/lib/utils.py
grr/proto/grr_response_proto/rrg.proto
grr/proto/grr_response_proto/rrg/action/list_interfaces.proto
grr/proto/grr_response_proto/rrg/action/list_mounts.proto
grr/proto/grr_response_proto/rrg/fs.proto
grr/proto/grr_response_proto/rrg/net.proto
grr/server/grr_response_server/artifact.py
grr/server/grr_response_server/artifact_test.py
grr/server/grr_response_server/fleetspeak_connector.py
grr/server/grr_response_server/flows/general/administrative.py
grr/server/grr_response_server/flows/general/administrative_test.py
grr/server/grr_response_server/flows/general/discovery.py
grr/server/grr_response_server/flows/general/discovery_test.py
grr/server/grr_response_server/gui/api_plugins/client.py
grr/server/grr_response_server/gui/api_plugins/client_test.py
grr/server/grr_response_server/gui/wsgiapp.py
grr/server/setup.py
grr/test/grr_response_test/lib/self_contained_config_writer.py
version.ini

* FileFinderOS bugfix for handling broken symlinks.
* Further decoupling interrogation from artifact parsers.
* Decoupling RRG protos from GRR protos.
* Updated fleetspeak-client-bin and fleetspeak-server-bin dependencies versions to 0.1.13.
* Butmping current version to 3.4.7.1.
* Adding changelog for 3.4.7.1 release.

Syncing recent changes.

---

.github/workflows/build.yml

The GRR Debian installer for the GRR server components is removed in
favor of a new docker image that contains all GRR components available
in the GitHub container registry
(https://github.com/google/grr/pkgs/container/grr). A new image is built
via GitHub actions with every push to the GRR GitHub repository.
The provided docker compose configuration file can be used to start
all GRR components using the new Docker image.

Replace Debian installer with Docker image and Docker compose stack

---

compose.yaml

grr-client container should wait until client's DEB package is available (right now it waits for any package to be there).

Update compose.yaml: preventing a race between building the client and waiting for it.

---

.github/workflows/build.yml

We do not provide M1 macs installers yet (fleetspeak-client-bin doesn't have M1 Fleetspeak binaries).

Update build.yml (switch macOS builds to Intel macs).

---

devenv/src/containers/grr/Containerfile

grpcio and grpcio-tools are effectively build-only dependency for GRR, but a runtime dependency for google-cloud-pubsub. To avoid versioning conflicts, we should install our own packages with separate `pip install` calls - this allows each call to override the version of grpcio or grpcio-tools if needed. This is clearly a hack. A proper fix is to migrate from setup.py to toml files and explicitly declare grpcio and grpcio-tools as GRR's build (and not runtime) dependencies.

Fixing grpcio dependency behavior in devenv GRR container.

---

Dockerfile
compose.yaml
docker_config_files/client/grr_fleetspeak_client.sh
docker_config_files/client/textservices/grr_client.service
docker_config_files/healthchecks/grr-client.sh

This PR proposes to add continous development functionality leveraging [Docker Compose Watch](https://docs.docker.com/compose/file-watch/)

Continuous Development with Docker Compose Watch

---

grr/core/grr_response_core/config/server.py
grr/server/grr_response_server/flows/general/large_file.py

This PR proposes an approach to autocreate signed URLs for large file upload with the Collect Large File flow.
- The approach taken is to autocreate the signed URLs in case the user (either via the UI or the API) creates a Collect Large File flow without submitting a signed URL.
- In case a Service Account (Server.signed_url_service_account_email) and a GCS Bucket (Server.signed_url_gcs_bucket_name) are configured and GRR is running on Google Kubernetes Engine (GKE) with Workload Identity Federation configured then the autocreation of the signed URL will succeed (see GRR documentation for more detail: https://grr-doc.readthedocs.io/en/latest/investigating-with-grr/collect-large-file.html).
- In case the above assumptions do not hold true then the Collect Large File flow will behave as it …

Adds functionality to autocreate signed URLs for large file upload

---

grr/core/grr_response_core/artifacts/makefile.py

This PR proposes to bump up the artifacts archive as the version currently used is dating back to June 2022.
The latest version available however is from March 2024.

Bumps up artifacts archive version

---

CHANGELOG.md
compose.yaml
grr/client_builder/grr_response_client_builder/client_build.py
grr/proto/grr_response_proto/api/signed_commands.proto
grr/proto/grr_response_proto/rrg/action/execute_signed_command.proto
grr/proto/grr_response_proto/signed_commands.proto
grr/server/grr_response_server/bin/command_signer.py
grr/server/grr_response_server/bin/command_signer_test.py
grr/server/grr_response_server/command_signer.py
grr/server/grr_response_server/command_signer_test_mixin.py
grr/server/grr_response_server/databases/db.py
grr/server/grr_response_server/databases/db_signed_commands_test.py
grr/server/grr_response_server/flows/general/cloud_test.py
grr/server/grr_response_server/flows/general/hardware_test.py
grr/server/grr_response_server/gui/api_plugins/signed_commands.py
grr/server/grr_response_server/gui/api_plugins/signed_commands_test.py
grr/server/grr_response_server/models/signed_commands_test.py
grr/server/grr_response_server/private_key_file_command_signer.py
version.ini

* Minor fixes in the client builder logic.
* Version bumped to 3490, CHANGELOG updated.
* Further RRG development.

Final touches before the 3490 release.
